### ISSUE TITLE
Server-rendering hydration warning in Next.js

### ISSUE THREAD

**Issue by srmagura** [algolia/docsearch#1242]
## Description

When `@docsearch/react` is used in Next.js (server-side rendering), React prints the warning:

```text
Warning: Expected server HTML to contain a matching <span> in <span>.
    at span
    at span
    at button
    at eval (webpack-internal:///./node_modules/@docsearch/react/dist/esm/DocSearchButton.js:28:32)
    at DocSearch (webpack-internal:///./node_modules/@docsearch/react/dist/esm/DocSearch.js:34:70)
    at div
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:39:27)
```

## Steps to reproduce

Clone my repo and follow the steps in the README: https://github.com/srmagura/docsearch-hydration-repro

## Expected behavior

There should be no hydration warning.

## Environment

- OS: Windows 11
- Browser: Chrome 96
- DocSearch version: 3.0.0-alpha.42

**Comment by shortcuts** [comment]
Hey @srmagura,

Does it happen only in `dev`?

**Comment by srmagura** [comment]
It does only happen in dev. If I run `next build` and `next start`, there is no hydration warning.

**Comment by nissy-dev** [comment]
@shortcuts 
After upgrading React v18, this error happens not only in dev but also in prod.

In dev

```
Warning: Expected server HTML to contain a matching <span> in <span>.
    at span
    at span
    at button
    at eval (webpack-internal:///./node_modules/@docsearch/react/dist/esm/DocSearchButton.js:28:32)
    at DocSearch (webpack-internal:///./node_modules/@docsearch/react/dist/esm/DocSearch.js:34:70)
    at header
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Header (webpack-internal:///./src/components/Header.tsx:32:94)
    at BaseLayout (webpack-internal:///./src/components/BaseLayout.tsx:16:23)
    at u (webpack-internal:///./node_modules/next-themes/dist/index.modern.js:11:246)
    at App (webpack-internal:///./src/pages/_app.tsx:39:24)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:241:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:861:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:1014:26)
```

In prod

```
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ia (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:54714)
    at ki (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:121976)
    at ys (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:109190)
    at vs (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:109118)
    at hs (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:108981)
    at rs (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:104089)
    at S (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:138179)
    at MessagePort.T (framework-0bb2f7917bc11482.js?__WB_REVISION__=0bb2f7917bc11482:1:138713)
```
