### ISSUE TITLE
Docker operation error. Procedure

### ISSUE THREAD

**Issue by pptfz** [algolia/docsearch#1544]
System environment：CentOS7.6
docker version: 20.10.17

`docker run -it --env-file=/tmp/.env -e "CONFIG=$(cat /tmp/config.json | jq -r tostring)" algolia/docsearch-scraper`

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/src/index.py", line 119, in <module>
    run_config(environ['CONFIG'])
  File "/root/src/index.py", line 33, in run_config
    config = ConfigLoader(config)
  File "/root/src/config/config_loader.py", line 84, in __init__
    self._parse()
  File "/root/src/config/config_loader.py", line 120, in _parse
    self.selectors = SelectorsParser().parse(self.selectors)
  File "/root/src/config/selectors_parser.py", line 64, in parse
    if 'lvl0' in config_selectors:
TypeError: argument of type 'NoneType' is not iterable
```

cat /tmp/.env 
```
APPLICATION_ID=xxx
API_KEY=xxx
```

 cat /tmp/config.json 
```
{
	"index_name": "xxx",
	"start_urls": [
		"https://xxx.com"
	],
	"sitemap_urls": [
		"https://xxx.com/docs"
	]
}
```

How do we do that?

**Comment by shortcuts** [comment]
Hey! This issue should be opened on the docsearch-scraper repository: https://github.com/algolia/docsearch-scraper

**Comment by pptfz** [comment]
Okay, thank you
